version: "3.3"

services:
  database:
    container_name: devdjango_database
    image: postgres
    restart: always
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=devpro
      - POSTGRES_USER=devpro
    ports:
      - 5436:5432